import {authorize,cloudError,enqueue} from './cloud-admin';
import {literalPattern} from './product-standard';
export const cloudJob=(j:Record<string,any>)=>({id:j.id,model:j.payload?.model??(j.kind==='config_update'?'Cập nhật quy chuẩn':j.kind),color:j.payload?.color??null,status:j.status,created_at:j.created_at,finished_at:j.finished_at,error:j.result?.error,channels:j.result?.channels??{},dashboard_rebuilt:j.result?.dashboard_rebuilt??false});
export async function getCloudColors(request:Request){try{const {db}=await authorize(request,true);const {data,error}=await db.from('app_settings').select('value,revision').eq('key','apple_colors').single();if(error)throw error;return Response.json({...data.value,revision:data.revision},{headers:{'Cache-Control':'no-store'}});}catch(e){return cloudError(e);}}
export async function queueCloud(request:Request,kind:string){try{const text=await request.text();if(text.length>60000)return Response.json({error:'Dữ liệu quá lớn.'},{status:413});let payload;try{payload=JSON.parse(text);}catch{return Response.json({error:'JSON không hợp lệ.'},{status:400});}const {db}=await authorize(request,true);const settings=await db.from('app_settings').select('value,revision').eq('key','apple_colors').single();if(settings.error)throw settings.error;
 if(kind==='config_update'){if(payload.version!==1||!Array.isArray(payload.products)||payload.products.length>200)return Response.json({error:'Cấu hình không hợp lệ.'},{status:400});if(payload.expected_revision!==settings.data.revision)return Response.json({error:'Quy chuẩn đã thay đổi. Tải lại trang trước khi lưu.'},{status:409});}
 else{if(typeof payload.model!=='string'||!settings.data.value.products.some((r:{model:string})=>r.model===payload.model))return Response.json({error:'Model chưa được lưu.'},{status:400});if(kind==='verify_prices'&&(!Array.isArray(payload.channels)||!payload.channels.length||payload.channels.some((s:string)=>!['tgdd','cellphones','fpt','viettel','phongvu'].includes(s))))return Response.json({error:'Kênh không hợp lệ.'},{status:400});payload.expected_revision=settings.data.revision;}
 const response=await enqueue(request,kind,payload);if(response.status===202){const d=await response.json();return Response.json({...d,job:cloudJob(d.job)},{status:202});}return response;
}catch(e){return cloudError(e);}}
export async function getCloudJobs(request:Request){try{const {db}=await authorize(request,true);const {data,error}=await db.from('automation_jobs').select('*').order('created_at',{ascending:false}).limit(30);if(error)throw error;const model=new URL(request.url).searchParams.get('model');const all=data.map(cloudJob);return Response.json({ok:true,jobs:all.filter(j=>!model||j.model===model||j.model==='Cập nhật quy chuẩn'),active:all.find(j=>['pending','running'].includes(j.status))??null,cli_workers:{}},{headers:{'Cache-Control':'no-store'}});}catch(e){return cloudError(e);}}
export async function getCloudUrls(request:Request){try{const {db}=await authorize(request,true);const r=await db.from('app_settings').select('value').eq('key','apple_url_checks').maybeSingle();if(r.error)throw r.error;return Response.json({ok:true,statuses:r.data?.value??{}},{headers:{'Cache-Control':'no-store'}});}catch(e){return cloudError(e);}}
export async function previewCloud(request:Request){try{const {db}=await authorize(request,true);const text=await request.text();if(text.length>10000)return Response.json({error:'Dữ liệu quá lớn.'},{status:413});const {rule,rename_from}=JSON.parse(text);if(!rule||typeof rule.model!=='string'||!(rule.color===null||typeof rule.color==='string')||!Array.isArray(rule.aliases)||rule.aliases.some((a:unknown)=>typeof a!=='string'))return Response.json({error:'Model/màu không hợp lệ.'},{status:400});const settings=await db.from('app_settings').select('value').eq('key','apple_models').single();if(settings.error)throw settings.error;const old=settings.data.value.models.find((m:{name:string})=>m.name===(rename_from||rule.model));const pattern=new RegExp(old&&!old.generated?old.pattern:literalPattern(rule.model),'i');const snapshots=await db.from('dashboard_snapshots').select('chain_name,payload').order('business_date',{ascending:false}).limit(35);if(snapshots.error)throw snapshots.error;const key=(v:unknown)=>String(v??'').normalize('NFC').trim().toLowerCase();const desired=new Set([rule.color,...rule.aliases].map(key));const names=new Set([rule.model,rename_from,...(old?.previous_names??[])].map(key));const checks=[];
 for(const [chain,label] of [['TGDD','MW'],['CellphoneS','CPS'],['FPT Shop','FPT'],['Viettel Store','Viettel'],['Phong Vũ','Phong Vũ']]){const matched=(snapshots.data??[]).filter(s=>s.chain_name===chain).flatMap(s=>s.payload.rows??[]).filter((r:{product_name:string})=>pattern.test(r.product_name));const bySku=new Map<string,Record<string,any>>();for(const r of matched.sort((a:Record<string,any>,b:Record<string,any>)=>String(b.observed_at).localeCompare(String(a.observed_at))))if(!bySku.has(r.sku))bySku.set(r.sku,r);const rows=[...bySku.values()];let verified=0,stale=0;for(const r of rows){const p=r.color_evidence;if(!rule.color)verified++;else if(p&&names.has(key(p.model))&&desired.has(key(p.canonical_color))&&String(p.product_code)===String(r.variant_id)&&p.website_color_id!=null&&p.verified_at)verified++;else if(p)stale++;}let links=0,links_ready=0;const latest=await db.from('discovery_runs').select('id').eq('chain_name',chain).order('completed_at',{ascending:false}).limit(1);if(latest.error)throw latest.error;const run=latest.data?.[0];if(run){for(let offset=0;offset<50000;offset+=500){const batch=await db.from('discovered_products').select('config,status,source_url').eq('run_id',run.id).order('source_url').range(offset,offset+499);if(batch.error)throw batch.error;for(const c of batch.data??[]){const name=c.config.source_product_name||c.config.product_name||c.config.discovered_name||'';if(pattern.test(name)){links++;if(c.status==='ready')links_ready++;}}if((batch.data??[]).length<500)break;}}checks.push({chain:label,links,links_ready,records:rows.length,verified,stale_proofs:stale,colors:[...new Set(rows.map(r=>r.color).filter(Boolean))],color_available:rows.some(r=>desired.has(key(r.color))),catalog_not_loaded:!run});}
 return Response.json({checks,note:'Đối chiếu catalog và snapshot đã lưu; đây không phải lượt cào website mới.'},{headers:{'Cache-Control':'no-store'}});
}catch(e){return cloudError(e);}}
