'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {cellPrice,matrix,quoteDay,latestQuotes,type Quote} from '@/lib/comparison';
import {datesForWeek,fiscalLabel,weekStart,money} from '@/lib/calendar';
import s from './comparison.module.css';
import LocalRefresh from './local-refresh';
import PriceFlash from './price-flash';
import WeeklyComparison from './weekly-comparison';
import {priceMovements,seriesKey} from '@/lib/price-movement';
import {useWatchlist} from '@/hooks/use-watchlist';
import {modelEntry} from '@/lib/watchlist';
type Source={warning?:string|null;slug:string;label:string;updated:string;issues:number;discovery:string;models:{model:string;status:string;records:number}[]};
type Data={view_start?:string|null;model_meta:Record<string,{brand:string;category:string}>;rows:Quote[];issues:{product_name:string;reason:string;chain:string;source_url:string}[];sources:Source[];models:string[]};
const compact=(v:number)=>new Intl.NumberFormat('vi-VN',{maximumFractionDigits:2}).format(v/1000000)+' tr';
const dateLabel=(v:string)=>new Intl.DateTimeFormat('vi-VN',{dateStyle:'short',timeZone:'Asia/Ho_Chi_Minh'}).format(new Date(v+'T00:00:00Z'));
const chains=['MW','CPS','FPT','VIETTEL','PV'];
export default function Comparison({data,mode='demo',userId=null,isAdmin=true,initialPeriod='latest'}:{data:Data;mode?:'demo'|'live';userId?:string|null;isAdmin?:boolean;initialPeriod?:'latest'|'day'|'week'}){
 const days=useMemo(()=>[...new Set(data.rows.map(quoteDay).filter(v=>!data.view_start||weekStart(v)===data.view_start))].sort().reverse(),[data]);
 const [day,setDay]=useState(days[0]??data.view_start??''),[period,setPeriod]=useState(initialPeriod),[query,setQuery]=useState(''),[brand,setBrand]=useState(''),[category,setCategory]=useState(''),[model,setModel]=useState(''),[chain,setChain]=useState(''),[manage,setManage]=useState(false),[modelQuery,setModelQuery]=useState(''),[selected,setSelected]=useState<{name:string;chain:string;quotes:Quote[]}|null>(null);
 const dialog=useRef<HTMLDialogElement>(null);
 const entries=useMemo(()=>data.models.map(name=>modelEntry({product_name:name,model_name:name,...data.model_meta[name]})),[data.models,data.model_meta]);
 const canEdit=mode==='demo'||isAdmin,watch=useWatchlist(mode,canEdit,entries),ready=watch.ready;
 const hidden=watch.state.models.filter(m=>watch.state.hidden.includes(m.id)).map(m=>m.name);
 const setHidden=(names:string[])=>{const ids=entries.filter(m=>names.includes(m.name)).map(m=>m.id);const other=watch.state.hidden.filter(id=>!entries.some(m=>m.id===id));watch.change({...watch.state,hidden:[...other,...ids]});};
 useEffect(()=>{if(selected)dialog.current?.showModal();else dialog.current?.close();},[selected]);
 const weekDays=datesForWeek(weekStart(day));
 const matches=(r:Quote)=>!hidden.includes(r.apple_model)&&(!brand||r.brand===brand)&&(!category||r.category===category)&&(!model||r.apple_model===model)&&(!chain||r.chain===chain)&&(!query||`${r.display_name} ${r.product_name} ${r.sku}`.toLocaleLowerCase('vi').includes(query.toLocaleLowerCase('vi')));
 const filtered=data.rows.filter(matches);
 const changes=ready?priceMovements(filtered,period==='latest'?(days[0]??data.view_start??''):day,period==='week'?weekDays:undefined):[];
 const periodRows=period==='latest'?latestQuotes(data.rows,days[0]??data.view_start??''):data.rows.filter(r=>period==='week'?weekDays.includes(quoteDay(r)):quoteDay(r)===day);
 const available=periodRows.filter(r=>!hidden.includes(r.apple_model)&&(!brand||r.brand===brand)&&(!category||r.category===category)&&(!model||r.apple_model===model)&&(!query||`${r.display_name} ${r.product_name} ${r.sku}`.toLocaleLowerCase('vi').includes(query.toLocaleLowerCase('vi'))));
 const table=matrix(available);
 if(!query&&!category){for(const m of data.models){if(!hidden.includes(m)&&(!brand||data.model_meta[m]?.brand===brand)&&(!model||model===m)&&!table.some(r=>r.model===m))table.push({key:'missing:'+m,model:m,name:m,variant:'Chưa có dữ liệu đúng cấu hình',cells:{}});}table.sort((a,b)=>data.models.indexOf(a.model)-data.models.indexOf(b.model));}const shownChains=chain?[chain]:chains;const categories=[...new Set(data.rows.filter(r=>!brand||r.brand===brand).map(r=>r.category).filter(Boolean))];const brands=[...new Set(data.rows.map(r=>r.brand).filter(Boolean))].sort();const modelOptions=data.models.filter(m=>(!brand||data.model_meta[m]?.brand===brand)&&(!category||data.model_meta[m]?.category===category));

 return <main className={s.page}>
 <header className={s.header}><div><span className={s.eyebrow}>BẢNG GIÁ CHO ĐỘI NGŨ CS</span><h1>Weekly Price CS</h1><p>{fiscalLabel(weekStart(day))} · Giá bán và CTKM của tất cả hãng · Apple theo màu đã cấu hình</p></div><div className={s.actions}>{isAdmin&&<a href="/apple-products">Quản lý Apple</a>}<a href="/history">Lịch sử ngày / tuần</a>{canEdit&&<button onClick={()=>setManage(!manage)}>Sản phẩm theo dõi</button>}</div></header>
 <div className={s.toolbar}><div className={s.segment}><button aria-pressed={period==='latest'} onClick={()=>setPeriod('latest')}>Giá gần nhất</button><button aria-pressed={period==='day'} onClick={()=>setPeriod('day')}>Theo ngày</button><button aria-pressed={period==='week'} onClick={()=>setPeriod('week')}>Theo tuần</button></div>{period==='week'?<select aria-label="Chọn tuần" value={weekStart(day)} onChange={e=>setDay(e.target.value)}>{[...new Set(days.map(weekStart))].map(v=><option key={v} value={v}>{fiscalLabel(v)} · {dateLabel(v)} – {dateLabel(datesForWeek(v)[6])}</option>)}</select>:<select aria-label="Chọn ngày" value={day} onChange={e=>{setDay(e.target.value);if(period==='latest')setPeriod('day');}}>{days.map(v=><option key={v} value={v}>{dateLabel(v)}</option>)}</select>}<input aria-label="Tìm sản phẩm" placeholder="Tìm model, dung lượng hoặc SKU…" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Chọn hãng" value={brand} onChange={e=>{setBrand(e.target.value);setCategory('');setModel('');}}><option value="">Tất cả hãng</option>{brands.map(b=><option key={b}>{b}</option>)}</select><select aria-label="Chọn danh mục" value={category} onChange={e=>{setCategory(e.target.value);setModel('');}}><option value="">Tất cả danh mục</option>{categories.map(c=><option key={c}>{c}</option>)}</select><select aria-label="Chọn model" value={model} onChange={e=>setModel(e.target.value)}><option value="">Tất cả model</option>{modelOptions.map(m=><option key={m}>{m}</option>)}</select><select aria-label="Chọn kênh" value={chain} onChange={e=>setChain(e.target.value)}><option value="">Tất cả kênh</option>{chains.map(c=><option key={c}>{c}</option>)}</select></div>
 {mode==='demo'&&<LocalRefresh/>}
 {period==='day'&&<p className={s.hint}>Dữ liệu cào đúng ngày {dateLabel(day)}: {chains.map(c=>`${c} ${data.rows.filter(r=>r.chain===c&&quoteDay(r)===day).length} SKU`).join(' · ')}. Ô trống là chưa có bản ghi đúng ngày; giá ngày trước chỉ xem trong “Giá gần nhất”.</p>}
 {period==='latest'&&<p className={s.hint}>Đang hiển thị bản ghi gần nhất của từng SKU trong dữ liệu đã tải. Ngày cập nhật ghi ngay dưới mỗi ô; giá ngày trước chưa được xác minh lại hôm nay. Chọn “Theo ngày” để chỉ xem dữ liệu cào đúng ngày.</p>}

 {ready&&<PriceFlash basis={period==='week'?'week':'day'} changes={changes} onSelect={m=>setSelected({name:m.after.display_name+' · Biến động giá',chain:m.after.chain,quotes:[m.before,m.after]})}/>}
 {manage&&canEdit&&<section className={s.manager}><h2>Sản phẩm theo dõi</h2><p>{mode==='live'?'Danh sách áp dụng cho tất cả người xem Web.':'Lựa chọn lưu trên trình duyệt.'} Không thay đổi bot hoặc báo cáo Telegram nhóm.</p><input aria-label="Tìm model theo dõi" placeholder="Tìm model…" value={modelQuery} onChange={e=>setModelQuery(e.target.value)}/><div className={s.actions}><button onClick={()=>setHidden([])}>Chọn tất cả</button><button onClick={()=>setHidden(data.models)}>Bỏ chọn tất cả</button><button onClick={()=>setHidden([])}>Khôi phục mặc định</button></div><div className={s.checks}>{[...new Set(entries.map(e=>e.category))].map(group=>{const models=entries.filter(e=>e.category===group&&e.name.toLowerCase().includes(modelQuery.toLowerCase()));return models.length?<fieldset key={group} style={{border:'1px solid #d6e2dc',borderRadius:8,padding:12}}><legend>{group}</legend>{models.map(m=><label key={m.id}><input type="checkbox" checked={!hidden.includes(m.name)} onChange={e=>setHidden(e.target.checked?hidden.filter(v=>v!==m.name):[...hidden,m.name])}/>{m.name}{watch.state.fresh.includes(m.id)&&<small>Mới</small>}</label>)}</fieldset>:null;})}</div></section>}
 <div className={s.caption}><span>{period==='week'?`${new Set(available.filter(r=>shownChains.includes(r.chain)).map(seriesKey)).size} SKU/kênh`: `${table.length} dòng`} · {data.models.filter(m=>!hidden.includes(m)).length} model theo dõi · {data.models.filter(m=>hidden.includes(m)).length} model ẩn</span><span>{period==='week'?'↓ Giảm · ↑ Tăng · So tuần này với tuần trước':<>↓ Giảm: đỏ · ↑ Tăng: xanh · <b className={s.flag}>!</b> Có trạng thái/CTKM</>} · Bấm giá để xem chi tiết</span></div>{watch.error&&<p role="alert">{watch.error} <button onClick={watch.onRetry}>Thử lại</button></p>}
 {period==='week'?<WeeklyComparison key={[weekStart(day),brand,category,model,chain,query,...hidden].join('|')} rows={ready?filtered:[]} days={weekDays} models={data.models} onSelect={quotes=>setSelected({name:quotes[0].display_name,chain:quotes[0].chain,quotes})}/>:<div className={s.scroll}><table className={s.table}><thead><tr><th>BASE MODEL</th>{shownChains.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{ready&&table.map(row=>{const cells=shownChains.map(c=>cellPrice(row.cells[c]??[]));return <tr key={row.key}><th scope="row">{row.name}{row.variant&&<small>{row.variant}</small>}</th>{shownChains.map((c,i)=>{const quotes=row.cells[c]??[],p=cells[i],hasNotes=quotes.some(q=>q.promo_text||q.promotion_complete===false);const cellChanges=changes.filter(m=>quotes.some(q=>q.chain===m.after.chain&&q.sku===m.after.sku));const direction=cellChanges.length&&cellChanges.every(m=>m.delta<0)?s.decrease:cellChanges.length&&cellChanges.every(m=>m.delta>0)?s.increase:'';return <td key={c} className={`${direction} ${quotes.length&&!p?s.status:''} ${hasNotes?s.noted:''}`}><button aria-label={`${row.name}, ${c}: ${p?money(p.min):quotes.length?'Không hiện giá':'Chưa có dữ liệu'}`} onClick={()=>setSelected({name:row.name+(row.variant?' · '+row.variant:''),chain:c,quotes})}>{p?(p.min===p.max?compact(p.min):`${compact(p.min)} – ${compact(p.max)}`):quotes.length?'Không hiện giá':'—'}{hasNotes&&<span className={s.flag} aria-label="Có ghi chú">!</span>}{quotes.map(q=>{const change=changes.find(m=>m.after.chain===q.chain&&m.after.sku===q.sku);return change?<small key={q.sku} className={change.delta<0?s.down:s.up}>{change.delta<0?'↓ Giảm':'↑ Tăng'} {money(Math.abs(change.delta))} · so {dateLabel(quoteDay(change.before))}</small>:null;})}{period==='latest'&&quotes.length>0&&<small>Cập nhật: {[...new Set(quotes.map(quoteDay))].sort().map(dateLabel).join(', ')}</small>}{quotes.length>1&&<small>{quotes.length} SKU · xem chi tiết</small>}</button></td>;})}</tr>;})}</tbody></table>{ready&&!table.length&&<p className={s.empty}>Không có dữ liệu phù hợp bộ lọc. Thử bật lại model hoặc chọn ngày khác.</p>}</div>}
 <p className={s.hint}>Vuốt ngang trên điện thoại để xem các kênh. “—” là chưa có dữ liệu, không có nghĩa hết hàng. Nếu website vẫn hiện giá khi hết hàng, bảng vẫn giữ giá đó.</p>
 <details className={s.coverage}><summary>Độ đầy đủ nguồn và các mục cần đối chiếu</summary><div className={s.sources}>{data.sources.map(source=><article key={source.slug}><b>{source.label}</b>{source.warning&&<p className={s.warning}>{source.warning}</p>}<p>{source.discovery} nguồn danh mục · {source.issues} mục cần đối chiếu</p><p>Cập nhật: {new Date(source.updated).toLocaleString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh'})}</p>{mode==='demo'&&<a href={`/${source.slug==='tgdd'?'mw':source.slug==='cellphones'?'cps':source.slug}-review.html`}>Xem kết quả bot ↗</a>}<small>{source.models.filter(m=>m.status==='missing_catalog').map(m=>m.model).join(', ')||'Không có model thiếu link trong danh sách hiện tại.'}</small></article>)}</div><p>Đọc được trang danh mục chưa bảo đảm đủ mọi model. Kiểm tra cảnh báo từng kênh và thời điểm của từng SKU; ô trống không có nghĩa là hết hàng.</p></details>
 <dialog ref={dialog} className={s.dialog} onClose={()=>setSelected(null)} onClick={e=>{if(e.target===e.currentTarget)setSelected(null);}}><div className={s.dialogHeader}><div><span className={s.eyebrow}>{selected?.chain}</span><h2>{selected?.name}</h2></div><button aria-label="Đóng chi tiết" onClick={()=>setSelected(null)}>✕</button></div>{selected&&!selected.quotes.length?<p>Chưa có bản ghi đúng model/cấu hình/màu trong phạm vi đang xem. Không thể kết luận hết hàng hoặc ngừng kinh doanh.</p>:selected?.quotes.map(q=><article className={s.quote} key={q.sku+q.observed_at}><strong>{q.promo_price!==null?money(q.promo_price):'Website không hiện giá'}</strong><dl><dt>{q.apple_selection==='unconfigured'||q.apple_selection==='other'?'Màu nguồn':'Màu theo dõi'}</dt><dd>{q.source_color||q.color||'Không có thông tin'}{q.apple_selection==='unconfigured'&&<small> · Chưa cấu hình màu theo dõi cho model này</small>}</dd><dt>SKU</dt><dd>{q.sku}</dd>{q.stale_since&&<><dt>Cảnh báo</dt><dd role="note" style={{color:'#9a6a12'}}>Dữ liệu cũ — {q.stale_reason||`lượt xác minh ${q.stale_since} chưa đọc lại được`}</dd></>}<dt>Tên nguồn</dt><dd>{q.product_name}</dd><dt>Cập nhật</dt><dd>{new Date(q.observed_at).toLocaleString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh'})}</dd></dl><h3>Trạng thái & khuyến mãi</h3><p className={s.notes}>{q.promo_text||'Không có ghi chú trong dữ liệu đã xác minh.'}</p>{q.promotion_complete===false&&<p className={s.warning}>Thông tin CTKM chưa được xác minh đầy đủ.</p>}<a target="_blank" rel="noopener noreferrer" href={q.source_url}>Mở trang đại lý ↗</a></article>)}</dialog>
 </main>;
}
