'use client';
import {useEffect,useState,useRef} from 'react';
import CloudGate,{useCloudAuth} from './cloud-gate';
import Comparison from './comparison';
import {loadComparison} from '@/lib/load-comparison';
import {apiFetch} from '@/lib/api-fetch';
import {supabase} from '@/lib/supabase';
import {weekStart,addDays,fiscalLabel} from '@/lib/calendar';
import type {ComponentProps} from 'react';
type Data=ComponentProps<typeof Comparison>['data'];
// "Sản phẩm theo dõi" = danh sách model Apple admin quản lý; Web chỉ hiện các model này.
function trackedOnly(d:Data&{preferences?:{products?:{model:string}[]}}):Data{const tracked=d.preferences?.products?.map(p=>p.model);if(!tracked)return d;return {...d,rows:d.rows.filter(r=>r.apple_selection==='selected'&&tracked.includes(r.apple_model)),models:tracked};}
function Content({initialPeriod}:{initialPeriod:'latest'|'day'|'week'}){const auth=useCloudAuth();const loadedStart=useRef('');useEffect(()=>{const timer=setInterval(()=>setRefresh(n=>n+1),60000);return()=>clearInterval(timer);},[]);const [start,setStart]=useState(weekStart(new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()))),[data,setData]=useState<ComponentProps<typeof Comparison>['data']|null>(null),[error,setError]=useState(''),[refresh,setRefresh]=useState(0);useEffect(()=>{const controller=new AbortController();if(loadedStart.current!==start)setData(null);loadedStart.current=start;setError('');loadComparison<ComponentProps<typeof Comparison>['data']>(start,controller.signal,apiFetch).then(d=>setData(trackedOnly(d))).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>controller.abort();},[start,refresh]);return <><div style={{display:'flex',flexWrap:'wrap',gap:12,padding:'16px 28px',alignItems:'center'}}><label>Tuần tài chính <select aria-label="Chọn tuần dữ liệu" value={start} onChange={e=>setStart(e.target.value)}>{Array.from({length:104},(_,i)=>addDays(weekStart(new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Ho_Chi_Minh'})),-7*i)).map(w=><option key={w} value={w}>{fiscalLabel(w)} · {w}</option>)}</select></label><button onClick={()=>setRefresh(n=>n+1)}>Làm mới dữ liệu</button>{auth?<button onClick={()=>void supabase().auth.signOut()}>Đăng xuất</button>:<a href="/apple-products">Đăng nhập quản trị</a>}</div>{error?<p role="alert" style={{padding:28}}>{error}</p>:!data?<p style={{padding:28}}>Đang tải bảng giá…</p>:!data.rows.length?<p style={{padding:28}}>Tuần này chưa có dữ liệu. Chọn tuần khác hoặc chạy bot.</p>:<Comparison key={start} data={data} initialPeriod={initialPeriod} mode="live" userId={auth?.userId??null} isAdmin={auth?.role==='admin'}/>}</>;}
export default function LiveComparison({initialPeriod='latest'}:{initialPeriod?:'latest'|'day'|'week'}){return <CloudGate optional={process.env.NEXT_PUBLIC_PUBLIC_VIEW==='true'}><Content initialPeriod={initialPeriod}/></CloudGate>;}
