'use client';
import {type Movement} from '@/lib/price-movement';
import {quoteDay,type Quote} from '@/lib/comparison';
import {money} from '@/lib/calendar';
import s from './comparison.module.css';
const date=(q:Quote)=>quoteDay(q).split('-').reverse().slice(0,2).join('/');
export default function PriceFlash({changes,onSelect,basis='day'}:{basis?:'day'|'week';changes:Movement[];onSelect:(m:Movement)=>void}){
 const drops=changes.filter(c=>c.delta<0).length,rises=changes.length-drops;
 return <section className={s.alerts} aria-label="Thông báo biến động giá"><div className={s.flash}><b>● PRICE FLASH</b>{changes.length?<div className={s.tickerViewport}><div className={s.tickerTrack}>{[0,1].map(copy=><div className={s.tickerGroup} key={copy} aria-hidden={copy===1||undefined}>{changes.slice(0,20).map(c=><button key={c.after.chain+c.after.sku} tabIndex={copy===1?-1:0} onClick={()=>onSelect(c)}>{c.after.chain} · {c.after.display_name}: {c.delta<0?'↓ Giảm':'↑ Tăng'} {money(Math.abs(c.delta))} · {date(c.before)} → {date(c.after)}</button>)}</div>)}</div></div>:<span className={s.flashEmpty}>{basis==='week'?'Chưa ghi nhận tăng/giảm giữa tuần này và tuần trước; SKU thiếu dữ liệu hai tuần không được tính.':'Chưa ghi nhận tăng/giảm giữa ngày đang xem và ngày liền trước; SKU thiếu một trong hai ngày không được tính.'}</span>}</div><details className={s.movementDetails}><summary>{drops} SKU giảm giá · {rises} SKU tăng giá · {changes.filter(c=>c.shock).length} biến động mạnh — Xem thông báo</summary><p>So sánh cùng SKU, màu và cấu hình. {basis==='week'?'So giá ghi nhận cuối tuần này với cuối tuần trước; ghi rõ ngày nguồn.':'So đúng ngày đang xem với ngày liền trước.'} Ngày thiếu dữ liệu không được xem là giá giữ nguyên. Danh sách theo bộ lọc và sản phẩm theo dõi của bạn.</p>{changes.length?<ul>{changes.slice(0,100).map(c=><li key={c.after.chain+c.after.sku}><button onClick={()=>onSelect(c)}><strong>{c.after.chain} · {c.after.display_name}</strong><span className={c.delta<0?s.down:s.up}>{c.delta<0?'↓ Giảm':'↑ Tăng'} {money(Math.abs(c.delta))} ({Math.abs(c.percent).toFixed(2)}%)</span><small>{money(c.before.promo_price!)} ({date(c.before)}) → {money(c.after.promo_price!)} ({date(c.after)}) · SKU {c.after.sku}</small></button></li>)}</ul>:<p>Chưa có biến động được xác minh. {basis==='week'?'Cần giá của cùng SKU trong cả tuần trước và tuần này.':'Cần giá của cùng SKU ở ngày đang xem và đúng ngày liền trước.'} Trạng thái không có giá chưa đủ để tính.</p>}{changes.length>100&&<p>Hiển thị 100 biến động lớn nhất trong {changes.length} biến động.</p>}</details></section>;
}
