'use client';
import {useState} from 'react';
import {dailySeries,weeklyPair} from '@/lib/price-movement';
import {quoteDay,type Quote} from '@/lib/comparison';
import {money,addDays,fiscalLabel} from '@/lib/calendar';
import s from './comparison.module.css';
const short=(p:number)=>new Intl.NumberFormat('vi-VN',{maximumFractionDigits:2}).format(p/1000000)+' tr';
const stamp=(q:Quote)=>quoteDay(q).split('-').reverse().slice(0,2).join('/');
export default function WeeklyComparison({rows,days,models,onSelect}:{rows:Quote[];days:string[];models:string[];onSelect:(q:Quote[])=>void}){
 const [limit,setLimit]=useState(100),[showDays,setShowDays]=useState(false);
 const series=[...dailySeries(rows).values()].filter(group=>days.some(day=>group.has(day))).sort((a,b)=>{const x=[...a.values()][0],y=[...b.values()][0];return models.indexOf(x.apple_model)-models.indexOf(y.apple_model)||x.display_name.localeCompare(y.display_name,'vi',{numeric:true})||x.chain.localeCompare(y.chain)||x.sku.localeCompare(y.sku);});
 const renderPrice=(q:Quote|undefined)=>q?<button onClick={()=>onSelect([q])}>{q.promo_price===null?'Chỉ trạng thái':short(q.promo_price)}<small>Ghi nhận {stamp(q)}</small></button>:<small className={s.noData}>Chưa có dữ liệu</small>;
 return <><p className={s.hint}>So {fiscalLabel(days[0])} với {fiscalLabel(addDays(days[0],-7))}. Dùng giá ghi nhận cuối mỗi tuần của cùng SKU/màu/cấu hình; tuần đang diễn ra dùng lần cào mới nhất. Thiếu tuần trước hoặc giá chỉ có trạng thái thì chưa tính tăng/giảm.</p><button aria-expanded={showDays} onClick={()=>setShowDays(!showDays)}>{showDays?'Ẩn chi tiết 7 ngày':'Xem chi tiết 7 ngày'}</button><div className={s.scroll} style={{marginTop:12}}><table className={`${s.table} ${s.weeklyTable}`} aria-label="So sánh tuần này với tuần trước"><thead><tr><th>MODEL / SKU</th><th>KÊNH</th><th>TUẦN TRƯỚC<small>{fiscalLabel(addDays(days[0],-7))}</small></th><th>TUẦN NÀY<small>{fiscalLabel(days[0])}</small></th><th>CHÊNH LỆCH TUẦN</th>{showDays&&days.map((day,i)=><th key={day}>{i===6?'CN':`T${i+2}`}<small>{day.split('-').reverse().slice(0,2).join('/')}</small></th>)}</tr></thead><tbody>{series.slice(0,limit).map((group,index)=>{const {before,after,change}=weeklyPair(group,days),q=after!,color=change&&change.delta<0?s.decrease:change&&change.delta>0?s.increase:'';return <tr key={index}><th scope="row">{q.display_name}<small>{q.display_variant} · {q.color||'Không lọc màu'} · SKU {q.sku}</small></th><td>{q.chain}</td><td>{renderPrice(before)}</td><td className={color}>{renderPrice(after)}</td><td className={color}>{change?<button onClick={()=>onSelect([change.before,change.after])}>{change.delta===0?'Không đổi':`${change.delta<0?'↓ Giảm':'↑ Tăng'} ${money(Math.abs(change.delta))}`}<small>{Math.abs(change.percent).toFixed(2)}% · {stamp(change.before)} → {stamp(change.after)}</small></button>:<small className={s.noData}>{!before?'Chưa có dữ liệu tuần trước':'Chưa đủ hai giá để so sánh'}</small>}</td>{showDays&&days.map(day=><td key={day}>{renderPrice(group.get(day))}</td>)}</tr>;})}</tbody></table>{!series.length&&<p className={s.empty}>Tuần này chưa có dữ liệu phù hợp bộ lọc.</p>}</div>{series.length>limit&&<button onClick={()=>setLimit(n=>n+100)}>Xem thêm 100 SKU ({Math.min(limit,series.length)}/{series.length})</button>}</>;
}
