'use client';
import {useState} from 'react';
import {dailySeries,movement} from '@/lib/price-movement';
import {type Quote} from '@/lib/comparison';
import {money} from '@/lib/calendar';
import s from './comparison.module.css';
const short=(p:number)=>new Intl.NumberFormat('vi-VN',{maximumFractionDigits:2}).format(p/1000000)+' tr';
export default function WeeklyComparison({rows,days,models,onSelect}:{rows:Quote[];days:string[];models:string[];onSelect:(q:Quote[])=>void}){
 const [limit,setLimit]=useState(100);
 const series=[...dailySeries(rows).values()].sort((a,b)=>{const x=[...a.values()][0],y=[...b.values()][0];return models.indexOf(x.apple_model)-models.indexOf(y.apple_model)||x.display_name.localeCompare(y.display_name,'vi',{numeric:true})||x.chain.localeCompare(y.chain)||x.sku.localeCompare(y.sku);});
 return <><p className={s.hint}>Bảng tuần hiển thị đồng thời cả 7 ngày, mỗi dòng là một SKU/kênh. Biến động tuần tính từ bản ghi đầu đến cuối tuần có dữ liệu; không tự lấp ngày thiếu.</p><div className={s.scroll}><table className={`${s.table} ${s.weeklyTable}`} aria-label="Biến động giá đủ 7 ngày"><thead><tr><th>MODEL / SKU</th><th>KÊNH</th>{days.map((day,i)=><th key={day}>{i===6?'CN':`T${i+2}`}<small>{day.split('-').reverse().slice(0,2).join('/')}</small></th>)}<th>BIẾN ĐỘNG TUẦN</th></tr></thead><tbody>{series.slice(0,limit).map((group,index)=>{const quotes=days.map(day=>group.get(day)).filter((q):q is Quote=>!!q),q=quotes[0],change=movement(quotes[0],quotes.at(-1));return <tr key={index}><th scope="row">{q.display_name}<small>{q.display_variant} · {q.color||'Không lọc màu'} · SKU {q.sku}</small></th><td>{q.chain}</td>{days.map(day=>{const current=group.get(day);return <td key={day}>{current?<button aria-label={`${q.display_name}, ${q.chain}, ${day}: ${current.promo_price===null?'Chỉ trạng thái':money(current.promo_price)}`} onClick={()=>onSelect([current])}>{current.promo_price===null?'Chỉ trạng thái':short(current.promo_price)}</button>:<small className={s.noData}>Chưa có dữ liệu</small>}</td>;})}<td>{change?<button onClick={()=>onSelect([change.before,change.after])} className={change.delta<0?s.down:change.delta>0?s.up:''}>{change.delta===0?'Không đổi':`${change.delta<0?'↓':'↑'} ${money(Math.abs(change.delta))}`}<small>{`${change.before.observed_at.slice(0,10)} → ${change.after.observed_at.slice(0,10)}`}</small></button>:<small className={s.noData}>Chưa đủ hai ngày có giá</small>}</td></tr>;})}</tbody></table>{!series.length&&<p className={s.empty}>Tuần này chưa có dữ liệu phù hợp bộ lọc.</p>}</div>{series.length>limit&&<button onClick={()=>setLimit(n=>n+100)}>Xem thêm 100 SKU ({Math.min(limit,series.length)}/{series.length})</button>}</>;
}
