import {authorize,cloudError} from '@/lib/cloud-admin';
export const dynamic='force-dynamic';
export async function GET(request:Request){try{
 const {db}=await authorize(request);const start=new URL(request.url).searchParams.get('start');let query=db.from('dashboard_snapshots').select('chain_name,business_date,payload').order('business_date',{ascending:false});
 if(start){if(!/^\d{4}-\d{2}-\d{2}$/.test(start)||Number.isNaN(Date.parse(start)))return Response.json({error:'Ngày không hợp lệ.'},{status:400});const end=new Date(start+'T00:00:00Z');end.setUTCDate(end.getUTCDate()+6);query=query.gte('business_date',start).lte('business_date',end.toISOString().slice(0,10));}else query=query.limit(35);
 const {data,error}=await query;if(error)throw error;const settings=await db.from('app_settings').select('key,value').in('key',['apple_colors','apple_models']);if(settings.error)throw settings.error;
 const prefs=settings.data.find(r=>r.key==='apple_colors')?.value??{version:1,products:[]};const rules=settings.data.find(r=>r.key==='apple_models')?.value?.models??[];const key=(v:unknown)=>String(v??'').normalize('NFC').trim().toLowerCase();const meta:Record<string,{brand:string;category:string}>={};const rows:Record<string,unknown>[]=[];const issues:Record<string,unknown>[]=[];const sources:Record<string,unknown>[]=[];const seen=new Set<string>(),sourceSeen=new Set<string>();
 for(const snap of data??[]){const payload=snap.payload;for(const r of payload.rows??[]){const matches=rules.filter((m:{pattern:string})=>new RegExp(m.pattern,'i').test(r.product_name));if(matches.length===1)r.apple_model=matches[0].name;
 const rule=prefs.products.find((p:{model:string})=>p.model===r.apple_model);if(rule?.color){const proof=r.color_evidence;const names=[rule.model,...(rule.previous_names??[])].map(key);const colors=[rule.color,...(rule.aliases??[])].map(key);if(!proof||!names.includes(key(proof.model))||!colors.includes(key(proof.canonical_color))||String(proof.product_code)!==String(r.variant_id)||proof.website_color_id==null||!proof.verified_at)continue;r.apple_selection='selected';r.color=rule.color;}else if(r.brand==='Apple')r.apple_selection=rule?'selected':'unconfigured';
 const id=JSON.stringify([r.slug,r.sku,r.observed_at]);if(!seen.has(id)){seen.add(id);rows.push(r);meta[r.apple_model]={brand:r.brand,category:r.category};}}issues.push(...(payload.issues??[]));if(payload.source&&!sourceSeen.has(snap.chain_name)){sourceSeen.add(snap.chain_name);sources.push(payload.source);}}
 for(const r of prefs.products)meta[r.model]??={brand:'Apple',category:r.model.startsWith('iPhone')?'Điện thoại':r.model.startsWith('iPad')?'Máy tính bảng':r.model.startsWith('Apple Watch')?'Đồng hồ thông minh':r.model.startsWith('AirPods')?'AirPods':'Máy tính xách tay'};
 const models=[...prefs.products.map((r:{model:string})=>r.model),...Object.keys(meta).filter(m=>!prefs.products.some((r:{model:string})=>r.model===m)).sort()];
 return Response.json({rows,issues,sources,models,model_meta:meta,preferences:prefs},{headers:{'Cache-Control':'no-store'}});
}catch(e){return cloudError(e);}}
